version: "3.9"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  order-db:
    image: postgres:15-alpine
    container_name: order-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  inventory-db:
    image: postgres:15-alpine
    container_name: inventory-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  packing-db:
    image: postgres:15-alpine
    container_name: packing-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: packing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  delivery-db:
    image: postgres:15-alpine
    container_name: delivery-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
