version: '3.8'

services:
  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master
    extra_hosts:
      - "api.cratemind.local:192.168.49.2"
      - "host.docker.internal:host-gateway"

  locust-worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    depends_on:
      - locust-master
    deploy:
      replicas: 3
    extra_hosts:
      - "api.cratemind.local:192.168.49.2"
      - "host.docker.internal:host-gateway"
