apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: cratemind/order-service:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-headless.default.svc.cluster.local:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/order_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
  - port: 8081
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: cratemind/inventory-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-headless.default.svc.cluster.local:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/inventory_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  ports:
  - port: 8082
  selector:
    app: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: cratemind/delivery-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-headless.default.svc.cluster.local:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/delivery_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: delivery-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: delivery-db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  ports:
  - port: 8084
  selector:
    app: delivery-service
